FROM node:lts-alpine3.22 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build


FROM node:lts-alpine3.22

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist


CMD ["serve", "-s", "dist", "-l", "5173"]