FROM node:lts-alpine3.22 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build --workspace=server


FROM node:lts-alpine3.22

WORKDIR /app

COPY package*.json ./
# COPY package
RUN npm install --omit=dev

COPY --from=builder /app/server/dist ./server/dist


CMD ["node", "server/dist/index.js"]