FROM node:lts-alpine3.22 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build --workspace=server


FROM node:lts-alpine3.22

WORKDIR /app

# dépendances runtime
COPY package*.json ./
RUN npm install --omit=dev

# code compilé
COPY --from=builder /app/server/dist ./server/dist

# IMPORTANT : dotenv ou config runtime
COPY server/.env ./server/.env

EXPOSE 3310

CMD ["node", "server/dist/index.js"]